name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: "./scripts/buildprod.sh"